// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: grpc.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ExampleApiService_GetProduct_FullMethodName          = "/example.api.ExampleApiService/GetProduct"
	ExampleApiService_ListProduct_FullMethodName         = "/example.api.ExampleApiService/ListProduct"
	ExampleApiService_CreateProduct_FullMethodName       = "/example.api.ExampleApiService/CreateProduct"
	ExampleApiService_UpdateProduct_FullMethodName       = "/example.api.ExampleApiService/UpdateProduct"
	ExampleApiService_PatchProduct_FullMethodName        = "/example.api.ExampleApiService/PatchProduct"
	ExampleApiService_DeleteProduct_FullMethodName       = "/example.api.ExampleApiService/DeleteProduct"
	ExampleApiService_GetProductReview_FullMethodName    = "/example.api.ExampleApiService/GetProductReview"
	ExampleApiService_ListProductReview_FullMethodName   = "/example.api.ExampleApiService/ListProductReview"
	ExampleApiService_CreateProductReview_FullMethodName = "/example.api.ExampleApiService/CreateProductReview"
	ExampleApiService_UpdateProductReview_FullMethodName = "/example.api.ExampleApiService/UpdateProductReview"
	ExampleApiService_PatchProductReview_FullMethodName  = "/example.api.ExampleApiService/PatchProductReview"
	ExampleApiService_DeleteProductReview_FullMethodName = "/example.api.ExampleApiService/DeleteProductReview"
	ExampleApiService_ArchiveProduct_FullMethodName      = "/example.api.ExampleApiService/ArchiveProduct"
)

// ExampleApiServiceClient is the client API for ExampleApiService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExampleApiServiceClient interface {
	GetProduct(ctx context.Context, in *GetProductRequest, opts ...grpc.CallOption) (*Product, error)
	ListProduct(ctx context.Context, in *ListProductRequest, opts ...grpc.CallOption) (*ListProductResponse, error)
	CreateProduct(ctx context.Context, in *CreateProductRequest, opts ...grpc.CallOption) (*Product, error)
	UpdateProduct(ctx context.Context, in *UpdateProductRequest, opts ...grpc.CallOption) (*Product, error)
	PatchProduct(ctx context.Context, in *PatchProductRequest, opts ...grpc.CallOption) (*Product, error)
	DeleteProduct(ctx context.Context, in *DeleteProductRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetProductReview(ctx context.Context, in *GetProductReviewRequest, opts ...grpc.CallOption) (*ProductReview, error)
	ListProductReview(ctx context.Context, in *ListProductReviewRequest, opts ...grpc.CallOption) (*ListProductReviewResponse, error)
	CreateProductReview(ctx context.Context, in *CreateProductReviewRequest, opts ...grpc.CallOption) (*ProductReview, error)
	UpdateProductReview(ctx context.Context, in *UpdateProductReviewRequest, opts ...grpc.CallOption) (*ProductReview, error)
	PatchProductReview(ctx context.Context, in *PatchProductReviewRequest, opts ...grpc.CallOption) (*ProductReview, error)
	DeleteProductReview(ctx context.Context, in *DeleteProductReviewRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ArchiveProduct(ctx context.Context, in *ArchiveProductRequest, opts ...grpc.CallOption) (*Product, error)
}

type exampleApiServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewExampleApiServiceClient(cc grpc.ClientConnInterface) ExampleApiServiceClient {
	return &exampleApiServiceClient{cc}
}

func (c *exampleApiServiceClient) GetProduct(ctx context.Context, in *GetProductRequest, opts ...grpc.CallOption) (*Product, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Product)
	err := c.cc.Invoke(ctx, ExampleApiService_GetProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exampleApiServiceClient) ListProduct(ctx context.Context, in *ListProductRequest, opts ...grpc.CallOption) (*ListProductResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProductResponse)
	err := c.cc.Invoke(ctx, ExampleApiService_ListProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exampleApiServiceClient) CreateProduct(ctx context.Context, in *CreateProductRequest, opts ...grpc.CallOption) (*Product, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Product)
	err := c.cc.Invoke(ctx, ExampleApiService_CreateProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exampleApiServiceClient) UpdateProduct(ctx context.Context, in *UpdateProductRequest, opts ...grpc.CallOption) (*Product, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Product)
	err := c.cc.Invoke(ctx, ExampleApiService_UpdateProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exampleApiServiceClient) PatchProduct(ctx context.Context, in *PatchProductRequest, opts ...grpc.CallOption) (*Product, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Product)
	err := c.cc.Invoke(ctx, ExampleApiService_PatchProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exampleApiServiceClient) DeleteProduct(ctx context.Context, in *DeleteProductRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ExampleApiService_DeleteProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exampleApiServiceClient) GetProductReview(ctx context.Context, in *GetProductReviewRequest, opts ...grpc.CallOption) (*ProductReview, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProductReview)
	err := c.cc.Invoke(ctx, ExampleApiService_GetProductReview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exampleApiServiceClient) ListProductReview(ctx context.Context, in *ListProductReviewRequest, opts ...grpc.CallOption) (*ListProductReviewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProductReviewResponse)
	err := c.cc.Invoke(ctx, ExampleApiService_ListProductReview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exampleApiServiceClient) CreateProductReview(ctx context.Context, in *CreateProductReviewRequest, opts ...grpc.CallOption) (*ProductReview, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProductReview)
	err := c.cc.Invoke(ctx, ExampleApiService_CreateProductReview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exampleApiServiceClient) UpdateProductReview(ctx context.Context, in *UpdateProductReviewRequest, opts ...grpc.CallOption) (*ProductReview, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProductReview)
	err := c.cc.Invoke(ctx, ExampleApiService_UpdateProductReview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exampleApiServiceClient) PatchProductReview(ctx context.Context, in *PatchProductReviewRequest, opts ...grpc.CallOption) (*ProductReview, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProductReview)
	err := c.cc.Invoke(ctx, ExampleApiService_PatchProductReview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exampleApiServiceClient) DeleteProductReview(ctx context.Context, in *DeleteProductReviewRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ExampleApiService_DeleteProductReview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exampleApiServiceClient) ArchiveProduct(ctx context.Context, in *ArchiveProductRequest, opts ...grpc.CallOption) (*Product, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Product)
	err := c.cc.Invoke(ctx, ExampleApiService_ArchiveProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExampleApiServiceServer is the server API for ExampleApiService service.
// All implementations should embed UnimplementedExampleApiServiceServer
// for forward compatibility.
type ExampleApiServiceServer interface {
	GetProduct(context.Context, *GetProductRequest) (*Product, error)
	ListProduct(context.Context, *ListProductRequest) (*ListProductResponse, error)
	CreateProduct(context.Context, *CreateProductRequest) (*Product, error)
	UpdateProduct(context.Context, *UpdateProductRequest) (*Product, error)
	PatchProduct(context.Context, *PatchProductRequest) (*Product, error)
	DeleteProduct(context.Context, *DeleteProductRequest) (*emptypb.Empty, error)
	GetProductReview(context.Context, *GetProductReviewRequest) (*ProductReview, error)
	ListProductReview(context.Context, *ListProductReviewRequest) (*ListProductReviewResponse, error)
	CreateProductReview(context.Context, *CreateProductReviewRequest) (*ProductReview, error)
	UpdateProductReview(context.Context, *UpdateProductReviewRequest) (*ProductReview, error)
	PatchProductReview(context.Context, *PatchProductReviewRequest) (*ProductReview, error)
	DeleteProductReview(context.Context, *DeleteProductReviewRequest) (*emptypb.Empty, error)
	ArchiveProduct(context.Context, *ArchiveProductRequest) (*Product, error)
}

// UnimplementedExampleApiServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExampleApiServiceServer struct{}

func (UnimplementedExampleApiServiceServer) GetProduct(context.Context, *GetProductRequest) (*Product, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProduct not implemented")
}
func (UnimplementedExampleApiServiceServer) ListProduct(context.Context, *ListProductRequest) (*ListProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProduct not implemented")
}
func (UnimplementedExampleApiServiceServer) CreateProduct(context.Context, *CreateProductRequest) (*Product, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProduct not implemented")
}
func (UnimplementedExampleApiServiceServer) UpdateProduct(context.Context, *UpdateProductRequest) (*Product, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProduct not implemented")
}
func (UnimplementedExampleApiServiceServer) PatchProduct(context.Context, *PatchProductRequest) (*Product, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PatchProduct not implemented")
}
func (UnimplementedExampleApiServiceServer) DeleteProduct(context.Context, *DeleteProductRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProduct not implemented")
}
func (UnimplementedExampleApiServiceServer) GetProductReview(context.Context, *GetProductReviewRequest) (*ProductReview, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProductReview not implemented")
}
func (UnimplementedExampleApiServiceServer) ListProductReview(context.Context, *ListProductReviewRequest) (*ListProductReviewResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProductReview not implemented")
}
func (UnimplementedExampleApiServiceServer) CreateProductReview(context.Context, *CreateProductReviewRequest) (*ProductReview, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProductReview not implemented")
}
func (UnimplementedExampleApiServiceServer) UpdateProductReview(context.Context, *UpdateProductReviewRequest) (*ProductReview, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProductReview not implemented")
}
func (UnimplementedExampleApiServiceServer) PatchProductReview(context.Context, *PatchProductReviewRequest) (*ProductReview, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PatchProductReview not implemented")
}
func (UnimplementedExampleApiServiceServer) DeleteProductReview(context.Context, *DeleteProductReviewRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProductReview not implemented")
}
func (UnimplementedExampleApiServiceServer) ArchiveProduct(context.Context, *ArchiveProductRequest) (*Product, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ArchiveProduct not implemented")
}
func (UnimplementedExampleApiServiceServer) testEmbeddedByValue() {}

// UnsafeExampleApiServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExampleApiServiceServer will
// result in compilation errors.
type UnsafeExampleApiServiceServer interface {
	mustEmbedUnimplementedExampleApiServiceServer()
}

func RegisterExampleApiServiceServer(s grpc.ServiceRegistrar, srv ExampleApiServiceServer) {
	// If the following call pancis, it indicates UnimplementedExampleApiServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ExampleApiService_ServiceDesc, srv)
}

func _ExampleApiService_GetProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExampleApiServiceServer).GetProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExampleApiService_GetProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExampleApiServiceServer).GetProduct(ctx, req.(*GetProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExampleApiService_ListProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExampleApiServiceServer).ListProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExampleApiService_ListProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExampleApiServiceServer).ListProduct(ctx, req.(*ListProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExampleApiService_CreateProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExampleApiServiceServer).CreateProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExampleApiService_CreateProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExampleApiServiceServer).CreateProduct(ctx, req.(*CreateProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExampleApiService_UpdateProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExampleApiServiceServer).UpdateProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExampleApiService_UpdateProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExampleApiServiceServer).UpdateProduct(ctx, req.(*UpdateProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExampleApiService_PatchProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PatchProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExampleApiServiceServer).PatchProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExampleApiService_PatchProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExampleApiServiceServer).PatchProduct(ctx, req.(*PatchProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExampleApiService_DeleteProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExampleApiServiceServer).DeleteProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExampleApiService_DeleteProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExampleApiServiceServer).DeleteProduct(ctx, req.(*DeleteProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExampleApiService_GetProductReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductReviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExampleApiServiceServer).GetProductReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExampleApiService_GetProductReview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExampleApiServiceServer).GetProductReview(ctx, req.(*GetProductReviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExampleApiService_ListProductReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProductReviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExampleApiServiceServer).ListProductReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExampleApiService_ListProductReview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExampleApiServiceServer).ListProductReview(ctx, req.(*ListProductReviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExampleApiService_CreateProductReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProductReviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExampleApiServiceServer).CreateProductReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExampleApiService_CreateProductReview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExampleApiServiceServer).CreateProductReview(ctx, req.(*CreateProductReviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExampleApiService_UpdateProductReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProductReviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExampleApiServiceServer).UpdateProductReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExampleApiService_UpdateProductReview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExampleApiServiceServer).UpdateProductReview(ctx, req.(*UpdateProductReviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExampleApiService_PatchProductReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PatchProductReviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExampleApiServiceServer).PatchProductReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExampleApiService_PatchProductReview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExampleApiServiceServer).PatchProductReview(ctx, req.(*PatchProductReviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExampleApiService_DeleteProductReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProductReviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExampleApiServiceServer).DeleteProductReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExampleApiService_DeleteProductReview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExampleApiServiceServer).DeleteProductReview(ctx, req.(*DeleteProductReviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExampleApiService_ArchiveProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArchiveProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExampleApiServiceServer).ArchiveProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExampleApiService_ArchiveProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExampleApiServiceServer).ArchiveProduct(ctx, req.(*ArchiveProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ExampleApiService_ServiceDesc is the grpc.ServiceDesc for ExampleApiService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExampleApiService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "example.api.ExampleApiService",
	HandlerType: (*ExampleApiServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProduct",
			Handler:    _ExampleApiService_GetProduct_Handler,
		},
		{
			MethodName: "ListProduct",
			Handler:    _ExampleApiService_ListProduct_Handler,
		},
		{
			MethodName: "CreateProduct",
			Handler:    _ExampleApiService_CreateProduct_Handler,
		},
		{
			MethodName: "UpdateProduct",
			Handler:    _ExampleApiService_UpdateProduct_Handler,
		},
		{
			MethodName: "PatchProduct",
			Handler:    _ExampleApiService_PatchProduct_Handler,
		},
		{
			MethodName: "DeleteProduct",
			Handler:    _ExampleApiService_DeleteProduct_Handler,
		},
		{
			MethodName: "GetProductReview",
			Handler:    _ExampleApiService_GetProductReview_Handler,
		},
		{
			MethodName: "ListProductReview",
			Handler:    _ExampleApiService_ListProductReview_Handler,
		},
		{
			MethodName: "CreateProductReview",
			Handler:    _ExampleApiService_CreateProductReview_Handler,
		},
		{
			MethodName: "UpdateProductReview",
			Handler:    _ExampleApiService_UpdateProductReview_Handler,
		},
		{
			MethodName: "PatchProductReview",
			Handler:    _ExampleApiService_PatchProductReview_Handler,
		},
		{
			MethodName: "DeleteProductReview",
			Handler:    _ExampleApiService_DeleteProductReview_Handler,
		},
		{
			MethodName: "ArchiveProduct",
			Handler:    _ExampleApiService_ArchiveProduct_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc.proto",
}
