package buf_test

import (
	"bytes"
	"io"
	"testing"

	"github.com/activatedio/apiinfra/genlib/grpc/buf"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestFile_Write(t *testing.T) {

	bufYamlFactory := func(unit buf.File) func(writer io.Writer) error {
		return unit.WriteBufYAML
	}

	bufGenYamlFactory := func(unit buf.File) func(writer io.Writer) error {
		return unit.WriteBufGenYAML
	}

	cases := []struct {
		name          string
		params        buf.FileParams
		expected      string
		writerFactory func(unit buf.File) func(w io.Writer) error
	}{
		{
			name:          "buf - simple",
			writerFactory: bufYamlFactory,
			params: buf.FileParams{
				WellKnownVersion: "v1",
				Modules: []buf.Module{
					{
						Name: "name1",
					},
				},
			},
			expected: `# Code generated by genlib/grpc/buf. DO NOT EDIT.
---
version: v2
modules:
  - name: name1
deps:
  - buf.build/googleapis/googleapis
  - buf.build/grpc-ecosystem/grpc-gateway
  - buf.build/protocolbuffers/wellknowntypes:v1
lint:
  use:
    - DEFAULT
  except:
    - FIELD_NOT_REQUIRED
    - PACKAGE_NO_IMPORT_CYCLE
  disallow_comment_ignores: true
breaking:
  use:
    - FILE
  except:
    - EXTENSION_NO_DELETE
    - FIELD_SAME_DEFAULT
`,
		},
		{
			name:          "buf - full",
			writerFactory: bufYamlFactory,
			params: buf.FileParams{
				WellKnownVersion: "v1.1.1",
				Modules: []buf.Module{
					{
						Name: "name1",
						Path: "path1/name1",
					},
					{
						Name: "name2",
						Path: "path2/name2",
					},
				},
			},
			expected: `# Code generated by genlib/grpc/buf. DO NOT EDIT.
---
version: v2
modules:
  - name: name1
    path: path1/name1
  - name: name2
    path: path2/name2
deps:
  - buf.build/googleapis/googleapis
  - buf.build/grpc-ecosystem/grpc-gateway
  - buf.build/protocolbuffers/wellknowntypes:v1.1.1
lint:
  use:
    - DEFAULT
  except:
    - FIELD_NOT_REQUIRED
    - PACKAGE_NO_IMPORT_CYCLE
  disallow_comment_ignores: true
breaking:
  use:
    - FILE
  except:
    - EXTENSION_NO_DELETE
    - FIELD_SAME_DEFAULT
`,
		},
		{
			name:          "buf gen",
			writerFactory: bufGenYamlFactory,
			params: buf.FileParams{
				ProtocolBuffersGoVersion: "v1",
				GrpcGoVersion:            "v2",
				GrpcGatewayVersion:       "v3",
				GoOutputPath:             "../gen/go",
			},
			expected: `# Code generated by genlib/grpc/buf. DO NOT EDIT.
---
version: v2
managed:
  enabled: true
plugins:
  - remote: buf.build/protocolbuffers/go:v1
    out: ../gen/go
    opt:
      - paths=source_relative
  - remote: buf.build/grpc/go:v2
    out: ../gen/go
    opt:
      - paths=source_relative
      - require_unimplemented_servers=false
  - remote: buf.build/grpc-ecosystem/gateway:v3
    out: ../gen/go
    opt:
      - paths=source_relative
`,
		},
	}

	for _, tt := range cases {
		t.Run(tt.name, func(t *testing.T) {

			b := &bytes.Buffer{}
			unit := buf.NewFile(tt.params)
			err := tt.writerFactory(unit)(b)

			require.NoError(t, err)
			res := b.String()
			assert.Equal(t, tt.expected, res)

		})
	}
}
