// Package buf provides helpers for generating buf configuration files.
package buf

import (
	"io"
	"text/template"
)

const (
	genGoContents = `// Code generated by genlib/grpc/buf. DO NOT EDIT.
package proto

{{ "" }}//go:generate go get -tool github.com/bufbuild/buf/cmd/buf
{{ "" }}//go:generate go tool github.com/bufbuild/buf/cmd/buf dep update
{{ "" }}//go:generate go tool github.com/bufbuild/buf/cmd/buf generate
`
	yamlContents = `# Code generated by genlib/grpc/buf. DO NOT EDIT.
---
version: v2
{{- if .Modules }}
modules:
{{- end }}
  {{- range .Modules }}
  - name: {{ .Name }}
    {{- if .Path }}
    path: {{ .Path }}
    {{- end }}
  {{- end }}
deps:
  - buf.build/googleapis/googleapis
  - buf.build/grpc-ecosystem/grpc-gateway
  - buf.build/protocolbuffers/wellknowntypes:{{ .WellKnownVersion }}
lint:
  use:
    - DEFAULT
  except:
    - FIELD_NOT_REQUIRED
    - PACKAGE_NO_IMPORT_CYCLE
  disallow_comment_ignores: true
breaking:
  use:
    - FILE
  except:
    - EXTENSION_NO_DELETE
    - FIELD_SAME_DEFAULT
`
	genYamlContents = `# Code generated by genlib/grpc/buf. DO NOT EDIT.
---
version: v2
managed:
  enabled: true
plugins:
  - remote: buf.build/protocolbuffers/go:{{ .ProtocolBuffersGoVersion }}
    out: {{ .GoOutputPath }}
    opt:
      - paths=source_relative
  - remote: buf.build/grpc/go:{{ .GrpcGoVersion }}
    out: {{ .GoOutputPath }}
    opt:
      - paths=source_relative
      - require_unimplemented_servers=false
  - remote: buf.build/grpc-ecosystem/gateway:{{ .GrpcGatewayVersion }}
    out: {{ .GoOutputPath }}
    opt:
      - paths=source_relative
`
)

type file struct {
	params FileParams
}

func (f *file) WriteBufGenYAML(w io.Writer) error {

	tmpl, err := template.New("file").Parse(genYamlContents)

	if err != nil {
		return err
	}

	return tmpl.Execute(w, &f.params)
}

func (f *file) WriteBufYAML(w io.Writer) error {

	tmpl, err := template.New("file").Parse(yamlContents)

	if err != nil {
		return err
	}

	return tmpl.Execute(w, &f.params)
}

func (f *file) WriteGenGo(w io.Writer) error {

	tmpl, err := template.New("file").Parse(genGoContents)

	if err != nil {
		return err
	}

	return tmpl.Execute(w, &f.params)
}

// NewFile returns a File configured with the supplied FileParams.
func NewFile(params FileParams) File {
	return &file{
		params: params,
	}
}
