// Code generated by genlib/grpc/buf. DO NOT EDIT.
package proto

//go:generate go get -tool github.com/bufbuild/buf/cmd/buf
//go:generate go tool github.com/bufbuild/buf/cmd/buf dep update
//go:generate go tool github.com/bufbuild/buf/cmd/buf generate
